export const discordLink = 'https://discord.com/invite/hQ9XvMUjjr'
export const forgejoLink = 'https://code.hypr.land/'
export const accountsLink = 'https://account.hypr.land/'
export const hyprperksLink = 'https://account.hypr.land/pricing'
export const forumLink = 'https://forum.hypr.land/'
